{"name": "新增收款单失败，收款单金额为空", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_case_fundsmanagement_receipt.py:23: AssumptionFailure\n>>\tpytest.assume(self.lp == udata['message'])\nAssertionError:", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_case_fundsmanagement_receipt.py:23: AssumptionFailure\nE               >>\tpytest.assume(self.lp == udata['message'])\nE               AssertionError:\n\nD:\\Pycharm\\Python\\venv\\lib\\site-packages\\six.py:718: FailedAssumption"}, "description": "基础设置-新增收款单用例", "attachments": [{"name": "点击输入客户名称", "source": "50b2a6f9-7bfc-41be-b869-b9e005c205e0-attachment.png", "type": "image/png"}, {"name": "选择客户", "source": "091d17a6-e406-4b16-af9a-7401d03f23a4-attachment.png", "type": "image/png"}, {"name": "清空日期", "source": "81669178-c8d1-475f-971f-60948125dfb7-attachment.png", "type": "image/png"}, {"name": "输入日期", "source": "14e0a825-77e3-44d2-b89d-f4ee34b93950-attachment.png", "type": "image/png"}, {"name": "输入账户", "source": "ce37ace6-0bce-4a60-9aea-807b40beb008-attachment.png", "type": "image/png"}, {"name": "选择账户", "source": "ed9a3c8e-9d3a-40c3-b61b-e1ae97a1caae-attachment.png", "type": "image/png"}, {"name": "点击金额", "source": "87f254bf-b696-456c-98a2-38df171809ea-attachment.png", "type": "image/png"}, {"name": "点击自动核销", "source": "c254311b-7217-4934-b567-809d5947a02e-attachment.png", "type": "image/png"}, {"name": "点击自动核销", "source": "5f02f02b-f10e-4aa3-9fd6-c237b3ed4ae2-attachment.png", "type": "image/png"}, {"name": "点击保存", "source": "2d02abdb-3ca9-4ac1-9c35-34b0d2bf8cb5-attachment.png", "type": "image/png"}, {"name": "断言信息", "source": "a2bf3638-fcde-4530-9a99-7656b4ca929a-attachment.txt", "type": "text/plain"}, {"name": "失败截图", "source": "15505769-21e6-4c2b-9554-7de93e53b187-attachment.png", "type": "image/png"}], "parameters": [{"name": "udata", "value": "{'Name': 'UI自动化新增收款单002', 'legend': '新增收款单失败，收款单金额为空', 'message': '请输入金额'}"}], "start": 1673079299675, "stop": 1673079326212, "uuid": "7473cfbe-3dce-4e2b-a6f5-c8b606d3097b", "historyId": "35d6170ef2be9ee7970c1f3e53a87e5b", "testCaseId": "ab461f05ee6d51df847c2ecc2686495b", "fullName": "test_case_fundsmanagement_receipt.TestCasereceipt#test_2_add_receipt", "labels": [{"name": "epic", "value": "资金管理"}, {"name": "story", "value": "新增收款单"}, {"name": "feature", "value": "收款单模块"}, {"name": "tag", "value": "@pytest.mark.usefixtures('Receipt')"}, {"name": "suite", "value": "test_case_fundsmanagement_receipt"}, {"name": "subSuite", "value": "TestCasereceipt"}, {"name": "host", "value": "DESKTOP-KEJFEBN"}, {"name": "thread", "value": "24804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_fundsmanagement_receipt"}]}