{"uuid": "ea65d88c-12ef-4f3e-afbb-f11b262d6bd9", "children": ["0ebdaa7d-5248-4ab2-89bd-6b4c9c05f587", "2fb90113-7c51-4516-88c1-fed1bcd592df", "892edef0-219a-4ff2-8015-e767b3bb0ea3", "f2a2324b-9a1a-40be-9af6-2529fe5db377", "15eaeee5-49a0-41fd-a5d4-46fdc3b4875b", "f31a178e-8434-4bac-a772-05077addc0a8", "f8ae578b-7a8c-47f2-9370-9fea9123078e", "330534a2-ec43-4ad0-ac58-8fb6d4dd56d4", "2a235661-57e6-4be4-9ccb-15d6a68385e5"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.198)\n\n", "trace": "  File \"D:\\Pycharm\\Python\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Pycharm\\Python\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Pycharm\\Python\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Pycharm\\UiYunDaiZhang\\UI2\\class_pytest_webdriver的副本\\conftest.py\", line 48, in init_driver\n    driver.maximize_window()\n  File \"D:\\Pycharm\\Python\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 737, in maximize_window\n    self.execute(command, params)\n  File \"D:\\Pycharm\\Python\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Pycharm\\Python\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1677319138653, "stop": 1677319146160}], "start": 1677319138653, "stop": 1677319146507}